/**
 * Copyright (c) 2017-present, Facebook, Inc.
 *
 * This source code is licensed under the MIT license found in the
 * LICENSE file in the root directory of this source tree.
 */
module.exports = {
  // samples: {
  //   // Features: ["mdx"],
  //   "React 基础示例": [],
  // },
  docs: [
    {
      type: 'category',
      label: '课程',
      collapsed: false,
      items: [
        // Computer System 类别
        {
          type: 'category',
          label: 'Computer SYSTEM',
          collapsed: false,
          items: [
            {
              type: 'autogenerated',
              dirName: 'course/computer-system',
            },
          ],
        },
        // Computer Algorithm 类别
        {
          type: 'category',
          label: 'COMPUTER ALGORITHM',
          collapsed: false,
          items: [
            {
              type: 'autogenerated',
              dirName: 'course/computer-algorithm',
            },
          ],
        },
        {
          type: 'category',
          label: 'ADVANCED CYBERSECURITY',
          collapsed: false,
          items: [
            {
              type: 'autogenerated',
              dirName: 'course/advanced-cybersecurity',
            },
          ],
        },
      ],
    },
  ],
  css_tutorials: [
    // "css/css-tutorial-intro",
    // {
    //   基础: ["css/basic/css-intro"],
    //   进阶: ["css/advanced/box-model"],
    // },
    {
      type: "autogenerated",
      dirName: "css",
    },
  ],
  // tools: {
  //   简介: ["tools/tools-intro"],
  //   "CSS 工具": ["tools/glassmorphism-generator/glassmorphism-generator"],
  // },
};